# site name
prefixName: 演员
siteName: UyoAhz
# favicon and site master avatar
favicon: https://q1.qlogo.cn/g?b=qq&nk=2496091142&s=640
avatar: https://q1.qlogo.cn/g?b=qq&nk=2496091142&s=640
url: https://uyoahz.cn
description: 集中精神，以气御剪
# cdn: https://cdn.jsdelivr.net/gh/Uyoahz26/cdn@master
pjax: 1
# 1开启
mathjax: 0

notice: 随缘更新~
lazyloadImg: https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives/, fa: fa-archive faa-shake , submenus: {
    标签: {path: /tags/,  fa: fa-tags}
  }}
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    歌单: {path: /music/, fa: fa-headphones faa-vertical },
    电影: {path: /movies/, fa: fa-youtube-play },
  } }
  留言: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  小赵叨叨: { path: /daodao/, fa: fa-commenting faa-wrench }
  友链: { path: /links/, fa: fa-link faa-shake }
  开往: { path: https://travellings.link/" target="_blank"", fa: fa-subway}
  关于: { path: /about, fa: fa-leaf faa-wrench  }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/cover/iu.jpg
  - https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/cover/iu2.jpg
  - https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/cover/ui3.jpg
  - https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/cover/567.jpg
  - https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/cover/mh13.jpg
  - https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/cover/mh14.jpg
  - https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/cover/IMG_20210526_212944.jpg
  - https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/blogImg/img/banner/20210606154950.jpg
  - https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/blogImg/img/banner/xiaobai.jpg
  - https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/blogImg/img/banner/xiaobai2.jpg
  - https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/blogImg/img/banner/xiaobai3.jpg


# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
# startdash: 
#   - {url: /daodao/, title: 叨叨, desc: 小赵叨叨, img: /img/startdash/sakura.md.png}
#   - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
#   - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}
  


# your site build time or founded date
siteBuildingTime: 02/02/2020

#social  url, img PC端配置
social:
  sina: {url: https://m.weibo.cn/u/1223178222, img: https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/social/sina.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=325959179, img: https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/social/wangyiyun.png}
  wechat: {url: /#, qrcode: https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/custom/weixin.jpg, img: https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/social/wechat.png}

#social  url, img 移动端配置
# msocial:
#   github: {url: http://github.com/honjun, fa: fa-github, color: 333}
#   weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
#   qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  alipay: https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/custom/donate/zfb.jpg
  wechat: https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/custom/donate/wechat.png
  wechatSQ: https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/img/custom/donate/wxzs.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/cdn/mp4
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: bgmp4.mp4,mengqi.mp4,kenan.mp4,20210606153748.mp4,20210606153826.mp4,manhua.mp4,alllice.mp4,shuye.mp4,iuiuiu.mp4,ncqy.mp4,xjzy.mp4

  

# 背景音乐
bg_music: https://blog-img-1258635493.cos.ap-chengdu.myqcloud.com/blogImg/mp3/20210606162136.mp3



# aplayer: 
#   id: 454285656
#   server: netease
#   type: playlist
#   fixed: true
#   autoplay: false
#   loop: all
#   order: random
#   preload: auto
#   volume: 0.7
#   mutex: true

# Valine
# valine: true
# v_appId: CATA3dWJhSdjJqov1ejub0kh-gzGzoHsz
# v_appKey: VsHS15UdeHhozWe0moFhxTi8
valine:
  enable: true # if you want use valine,please set this value is true
  appId: CATA3dWJhSdjJqov1ejub0kh-gzGzoHsz # leancloud application app id
  appKey: VsHS15UdeHhozWe0moFhxTi8 # leancloud application app key
  verify: true

# abbrlink config
abbrlink:
  alg: crc16  #support crc16(default) and crc32
  rep: dec    #support dec(default) and hex
  drafts: false #(true)Process draft,(false)Do not process draft
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
     enable: false
     depth:
